// Generated by CoffeeScript 1.6.3
(function() {
  var arr, i, myfunc, obj, _i, _len;

  obj = {
    name: "Sam",
    donkeys: true,
    getName: function() {
      return this.name;
    }
  };

  console.log(obj.getName());

  arr = "abcdefghijklmnopqrstuvwxyz";

  for (_i = 0, _len = arr.length; _i < _len; _i += 3) {
    i = arr[_i];
    console.log(i);
  }

  myfunc = function(name, family) {
    this.family = family;
    return this;
  };

}).call(this);
